apiVersion: v1
kind: Service
metadata:
  name: dataflows-WHATTHEENV
  labels:
    name: dataflows-WHATTHEENV
spec:
  type: LoadBalancer
  ports:
    - port: 22
      nodePort: 32502
      name: tcp
  selector:
    name: dataflows-WHATTHEENV